name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - staging
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'
      - name: Create environments folder
        run: mkdir -p src/environments
      - name: Install Dependencies
        run: npm install
      - name: Install Angular CLI Globally
        run: npm install -g @angular/cli
      - name: Create environment.ts (prod)
        if: github.ref_name == 'master'
        run: |
          cp src/environment.ts.template src/environments/environment.ts
          sed -i "s|YOUR_API_KEY|${{ secrets.APIKEY }}|g" src/environments/environment.ts
          sed -i "s|YOUR_AUTH_DOMAIN|${{ secrets.AUTHDOMAIN }}|g" src/environments/environment.ts
          sed -i "s|YOUR_PROJECT_ID|${{ secrets.PROJECTID }}|g" src/environments/environment.ts
          sed -i "s|YOUR_STORAGE_BUCKET|${{ secrets.STORAGEBUCKET }}|g" src/environments/environment.ts
          sed -i "s|YOUR_MESSAGING_SENDER_ID|${{ secrets.MESSAGINGSENDERID }}|g" src/environments/environment.ts
          sed -i "s|YOUR_APP_ID|${{ secrets.APPID }}|g" src/environments/environment.ts
          sed -i "s|YOUR_MEASUREMENT_ID|${{ secrets.MEASUREMENTID}}|g" src/environments/environment.ts
      - name: Create environment.ts (staging)
        if: github.ref_name == 'staging'
        run: |
          cp src/environment.staging.ts.template src/environments/environment.ts
          cp src/environment.staging.ts.template src/environments/environment.staging.ts
          sed -i "s|YOUR_API_KEY|${{ secrets.APIKEY }}|g" src/environments/environment.staging.ts
          sed -i "s|YOUR_AUTH_DOMAIN|${{ secrets.AUTHDOMAIN }}|g" src/environments/environment.staging.ts
          sed -i "s|YOUR_PROJECT_ID|${{ secrets.PROJECTID }}|g" src/environments/environment.staging.ts
          sed -i "s|YOUR_STORAGE_BUCKET|${{ secrets.STORAGEBUCKET }}|g" src/environments/environment.staging.ts
          sed -i "s|YOUR_MESSAGING_SENDER_ID|${{ secrets.MESSAGINGSENDERID }}|g" src/environments/environment.staging.ts
          sed -i "s|YOUR_APP_ID|${{ secrets.APPID }}|g" src/environments/environment.staging.ts
          sed -i "s|YOUR_MEASUREMENT_ID|${{ secrets.MEASUREMENTID}}|g" src/environments/environment.staging.ts
      - name: test Application (staging)
        run: npm run test
      - name: Build Application (staging)
        if: github.ref_name == 'staging'
        run: npm run build:staging
      - name: deploy Application on firebase hosting (staging)
        if: github.ref_name == 'staging'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_CODE_482D3 }}
          channelId: live
          projectId: game-code-482d3
          target: staging
      - name: Build Application (prod)
        if: github.ref_name == 'master'
        run: npm run build:prod
      - name: deploy Application on firebase hosting (prod)
        if: github.ref_name == 'master'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_CODE_482D3 }}
          channelId: live
          projectId: game-code-482d3
